Repository DSA8-4/EcoTrade-BE, pull requests merged in 2024-09, with the labels that each got.

#31 mypage 접근 수정
  src/main/java/com/example/board/config/SecurityConfig.java
  src/main/java/com/example/board/controller/MemberController.java
  src/main/java/com/example/board/dto/MemberProfileDto.java
  src/main/java/com/example/board/dto/MemberUpdateRequest.java
  src/main/java/com/example/board/model/member/Member.java
  src/main/java/com/example/board/model/member/MemberJoinForm.java
  src/main/java/com/example/board/service/MemberService.java
  src/main/java/com/example/board/util/JwtTokenProvider.java
Labels: Fix

#33 add category
  src/main/java/com/example/board/config/SecurityConfig.java
  src/main/java/com/example/board/controller/ProductController.java
  src/main/java/com/example/board/model/product/Category.java
  src/main/java/com/example/board/model/product/Product.java
  src/main/java/com/example/board/model/product/ProductWriteForm.java
  src/main/java/com/example/board/service/MemberService.java
  src/main/java/com/example/board/service/ProductService.java
Labels: Feat, Fix

#35 Fix productList infinite loop
  src/main/java/com/example/board/controller/ProductController.java
  src/main/java/com/example/board/dto/ProductDTO.java
  src/main/java/com/example/board/model/product/Product.java
Labels: Fix

#36 상품등록 할 때 멤버 아이디 설정
  src/main/java/com/example/board/controller/ProductController.java
  src/main/java/com/example/board/model/member/Member.java
  src/main/java/com/example/board/model/product/ProductWriteForm.java
  src/main/java/com/example/board/service/ProductService.java
Labels: Feat

#38 chat 전반적 수정
  src/main/java/com/example/board/config/SecurityConfig.java
  src/main/java/com/example/board/controller/ChatRestController.java
  src/main/java/com/example/board/controller/ChatStompController.java
  src/main/java/com/example/board/model/chat/ChatRoom.java
  src/main/java/com/example/board/model/member/Member.java
  src/main/java/com/example/board/model/product/Product.java
  src/main/java/com/example/board/model/product/ProductWriteForm.java
  src/main/java/com/example/board/service/ChatService.java
Labels: Fix

#39 Authorization 구현, Like Entity
  src/main/java/com/example/board/config/SecurityConfig.java
  src/main/java/com/example/board/controller/ProductController.java
  src/main/java/com/example/board/filter/JwtRequestFilter.java
  src/main/java/com/example/board/model/member/MemberJoinForm.java
  src/main/java/com/example/board/model/product/Image.java
  src/main/java/com/example/board/model/product/Like.java
  src/main/java/com/example/board/model/product/Product.java
  src/main/java/com/example/board/repository/LikeRepository.java
  src/main/java/com/example/board/service/MemberService.java
  src/main/java/com/example/board/service/ProductService.java
  src/main/java/com/example/board/util/JwtTokenProvider.java
  src/main/java/com/example/board/util/JwtTokenUtil.java
Labels: Feat

#46 거래상태 기능
  src/main/java/com/example/board/controller/ProductController.java
  src/main/java/com/example/board/model/product/Product.java
  src/main/java/com/example/board/model/product/ProductStatus.java
Labels: Feat

#48 상품 구매하기 기능
  src/main/java/com/example/board/controller/ProductController.java
  src/main/java/com/example/board/model/member/Member.java
  src/main/java/com/example/board/model/product/Product.java
  src/main/java/com/example/board/service/MemberService.java
  src/main/java/com/example/board/service/ProductService.java
Labels: Feat, Fix

#49 Memberservice sales 픽스
  src/main/java/com/example/board/controller/MemberController.java
  src/main/java/com/example/board/model/product/Sales.java
  src/main/java/com/example/board/repository/SalesRepository.java
  src/main/java/com/example/board/service/MemberService.java
Labels: Fix

#51 sales fix, resister member_id, name, email 중복체크 fix
  src/main/java/com/example/board/controller/MemberController.java
  src/main/java/com/example/board/repository/MemberRepository.java
  src/main/java/com/example/board/service/MemberService.java
Labels: Fix

#54 채팅방 생성 api
  src/main/java/com/example/board/controller/ChatRestController.java
  src/main/java/com/example/board/controller/ChatStompController.java
  src/main/java/com/example/board/controller/MemberController.java
  src/main/java/com/example/board/controller/ProductController.java
  src/main/java/com/example/board/dto/ChatRoomDTO.java
  src/main/java/com/example/board/dto/ProductDTO.java
  src/main/java/com/example/board/model/chat/ChatRoom.java
  src/main/java/com/example/board/model/chat/CreateRoomRequest.java
  src/main/java/com/example/board/model/product/Product.java
  src/main/java/com/example/board/repository/ChatRoomRepository.java
  src/main/java/com/example/board/service/ChatService.java
  src/main/java/com/example/board/util/JwtTokenProvider.java
Labels: Feat, Fix

#58 sellersPoint
  src/main/java/com/example/board/controller/ProductController.java
  src/main/java/com/example/board/model/product/Product.java
  src/main/java/com/example/board/repository/PurchaseRepository.java
  src/main/java/com/example/board/service/MemberService.java
Labels: Feat, Fix

#59 채팅 메세지 관련
  src/main/java/com/example/board/controller/ChatRestController.java
  src/main/java/com/example/board/controller/ChatStompController.java
  src/main/java/com/example/board/dto/ChatMessageDTO.java
  src/main/java/com/example/board/dto/ChatRoomWithLastMessageDTO.java
  src/main/java/com/example/board/model/chat/ChatMessage.java
  src/main/java/com/example/board/model/chat/ChatRoom.java
  src/main/java/com/example/board/repository/ChatMessageRepository.java
  src/main/java/com/example/board/repository/ChatRoomRepository.java
  src/main/java/com/example/board/service/ChatService.java
  src/main/java/com/example/board/util/JwtTokenProvider.java
Labels: Feat

#55 profileimage 추가
  src/main/java/com/example/board/controller/MemberController.java
  src/main/java/com/example/board/dto/MemberProfileDto.java
  src/main/java/com/example/board/model/member/Member.java
  src/main/java/com/example/board/model/member/ProfileImage.java
  src/main/java/com/example/board/model/member/ProfileImageRequest.java
  src/main/java/com/example/board/repository/ProfileImageRepository.java
  src/main/java/com/example/board/service/MemberService.java
Labels: Feat

#63 컨트롤러 수정
  src/main/java/com/example/board/controller/EcoProductController.java
  src/main/java/com/example/board/controller/ProductController.java
  src/main/java/com/example/board/dto/EcoProductDTO.java
  src/main/java/com/example/board/dto/ProductDTO.java
  src/main/java/com/example/board/model/ecoProduct/EcoProduct.java
  src/main/java/com/example/board/model/ecoProduct/EcoProductImage.java
  src/main/java/com/example/board/repository/EcoProductRepository.java
  src/main/java/com/example/board/service/EcoProductService.java
Labels: Fix

#65 상품구매내역 구현
  src/main/java/com/example/board/controller/MemberController.java
  src/main/java/com/example/board/dto/PurchaseDTO.java
  src/main/java/com/example/board/model/product/Purchase.java
  src/main/java/com/example/board/service/MemberService.java
Labels: Feat

#68 에코포인트 CRUD
  src/main/java/com/example/board/controller/EcoProductController.java
  src/main/java/com/example/board/model/ecoProduct/EcoProduct.java
  src/main/java/com/example/board/model/product/Purchase.java
  src/main/java/com/example/board/repository/EcoProductImageRepository.java
  src/main/java/com/example/board/repository/EcoProductRepository.java
  src/main/java/com/example/board/service/EcoProductService.java
Labels: Feat

#73 Fix ChatLastMessageDTO
  src/main/java/com/example/board/dto/ChatRoomWithLastMessageDTO.java
  src/main/java/com/example/board/service/ChatService.java
Labels: Fix

#74 product_id->id로 변경
  src/main/java/com/example/board/controller/EcoProductController.java
  src/main/java/com/example/board/controller/ProductController.java
  src/main/java/com/example/board/dto/ProductDTO.java
  src/main/java/com/example/board/model/product/Product.java
  src/main/java/com/example/board/model/product/Purchase.java
  src/main/java/com/example/board/service/MemberService.java
  src/main/java/com/example/board/service/ProductService.java
  src/main/java/com/example/board/util/JwtTokenProvider.java
Labels: Fix

#75 product_id->id
  src/main/java/com/example/board/dto/PurchaseDTO.java
  src/main/java/com/example/board/model/product/Purchase.java
  src/main/java/com/example/board/service/MemberService.java
  src/main/java/com/example/board/util/JwtTokenProvider.java
Labels: Fix

#78 삭제, 수정 권한 있는 사람만 가능
  src/main/java/com/example/board/controller/ProductController.java
Labels: Fix

#76 admin생성 매크로
  src/main/java/com/example/board/controller/AdminController.java
  src/main/java/com/example/board/service/AdminService.java
  src/main/java/com/example/board/util/MacroUtil.java
Labels: Feat

#82 ProfileImage를 Member안에 포함시키기
  src/main/java/com/example/board/controller/MemberController.java
  src/main/java/com/example/board/dto/MemberProfileDto.java
  src/main/java/com/example/board/dto/MemberUpdateRequest.java
  src/main/java/com/example/board/dto/PurchaseDTO.java
  src/main/java/com/example/board/model/member/Member.java
  src/main/java/com/example/board/model/member/ProfileImage.java
  src/main/java/com/example/board/model/product/Purchase.java
  src/main/java/com/example/board/repository/ProfileImageRepository.java
  src/main/java/com/example/board/service/MemberService.java
  src/main/java/com/example/board/util/MacroUtil.java
Labels: Fix

#81 detail 페이지에서 좋아요한 멤버 리스트 뜨게함
  src/main/java/com/example/board/controller/ProductController.java
  src/main/java/com/example/board/dto/ProductDTO.java
  src/main/java/com/example/board/model/product/Product.java
Labels: Feat, Fix

#84 Room with productId
  src/main/java/com/example/board/controller/ChatRestController.java
  src/main/java/com/example/board/dto/ChatRoomWithLastMessageDTO.java
  src/main/java/com/example/board/repository/ChatRoomRepository.java
  src/main/java/com/example/board/service/ChatService.java
Labels: Feat

#85 로그인 시 프로필 이미지를 가져오도록 수정
  src/main/java/com/example/board/controller/MemberController.java
Labels: Fix

#87 리스트 페이징
  src/main/java/com/example/board/controller/ProductController.java
  src/main/java/com/example/board/repository/ProductRepository.java
  src/main/java/com/example/board/service/ProductService.java
Labels: Feat

#88 fix listPage
  src/main/java/com/example/board/controller/ProductController.java
Labels: Fix

#90 Fix ecoProduct register
  src/main/java/com/example/board/controller/EcoProductController.java
  src/main/java/com/example/board/model/ecoProduct/EcoProductWriteForm.java
Labels: Fix

#91 ecoProductController 수정
  src/main/java/com/example/board/controller/EcoProductController.java
  src/main/java/com/example/board/model/member/Member.java
Labels: Fix
