Repository DSA8-4/EcoTrade-BE, pull requests merged in 2024-08, with the labels that each got.

#8 Product List
  src/main/java/com/example/board/controller/ProductController.java
  src/main/java/com/example/board/model/product/AttachedImage.java
  src/main/java/com/example/board/model/product/Product.java
  src/main/java/com/example/board/repository/ImageRepository.java
  src/main/java/com/example/board/repository/ProductRepository.java
  src/main/java/com/example/board/service/ProductService.java
  src/main/java/com/example/board/util/PageNavigator.java
Labels: Feat

#12 Temp
  src/main/java/com/example/board/controller/ProductController.java
  src/main/java/com/example/board/model/product/AttachedImage.java
  src/main/java/com/example/board/model/product/Product.java
  src/main/java/com/example/board/repository/ProductRepository.java
  src/main/java/com/example/board/service/ProductService.java
  src/main/java/com/example/board/util/ImageService.java
Labels: Fix

#10 feat: chat prototype
  build.gradle
  src/main/java/com/example/board/config/ChatConfig.java
  src/main/java/com/example/board/controller/ChatRestController.java
  src/main/java/com/example/board/controller/ChatStompController.java
  src/main/java/com/example/board/model/chat/ChatMessage.java
  src/main/java/com/example/board/model/chat/ChatRoom.java
  src/main/java/com/example/board/repository/ChatMessageRepository.java
  src/main/java/com/example/board/repository/ChatRoomRepository.java
  src/main/java/com/example/board/service/ChatService.java
Labels: Feat

#17 Spring Security 적용
  build.gradle
  src/main/java/com/example/board/config/SecurityConfig.java
  src/main/java/com/example/board/config/UserDetailsConfig.java
  src/main/java/com/example/board/config/WebConfig.java
  src/main/java/com/example/board/filter/JwtRequestFilter.java
  src/main/java/com/example/board/filter/LogFilter.java
  src/main/java/com/example/board/filter/LoginCheckFilter.java
  src/main/java/com/example/board/interceptor/LoginCheckInterceptor.java
  src/main/java/com/example/board/interceptor/LoginInterceptor.java
  src/main/java/com/example/board/util/JwtTokenUtil.java
Labels: Feat

#21 프로덕트업로드,프로덕트리스트,프로덕트상세
  src/main/java/com/example/board/config/SecurityConfig.java
  src/main/java/com/example/board/controller/ProductController.java
  src/main/java/com/example/board/service/ProductService.java
Labels: Feat, Fix

#18 Spring security Member에 적용
  src/main/java/com/example/board/config/SecurityConfig.java
  src/main/java/com/example/board/config/WebConfig.java
  src/main/java/com/example/board/controller/MemberController.java
  src/main/java/com/example/board/filter/JwtRequestFilter.java
  src/main/java/com/example/board/model/member/Member.java
  src/main/java/com/example/board/service/MemberService.java
  src/main/java/com/example/board/util/PasswordUtils.java
Labels: Feat

#22 login기능 fix
  build.gradle
  src/main/java/com/example/board/config/SecurityConfig.java
  src/main/java/com/example/board/controller/MemberController.java
  src/main/java/com/example/board/model/member/Member.java
  src/main/java/com/example/board/service/MemberService.java
  src/main/java/com/example/board/util/JwtTokenProvider.java
  src/main/java/com/example/board/util/PasswordUtils.java
Labels: Fix

#27 productUpdate feat
  src/main/java/com/example/board/config/SecurityConfig.java
  src/main/java/com/example/board/controller/ProductController.java
  src/main/java/com/example/board/model/product/ProductUpdateForm.java
  src/main/java/com/example/board/service/ProductService.java
Labels: Feat

#24 충돌해결
  src/main/java/com/example/board/EcoTradeApplication.java
  src/main/java/com/example/board/controller/ProductController.java
  src/main/java/com/example/board/model/product/Product.java
  src/main/java/com/example/board/service/ProductService.java
Labels: Feat
